config/routes.rb
Rails.application.routes.draw do
  root 'index#pages'
  get '/p/:pname-i.:pid', to: 'index#item_page', as: :item_page, constraints: {
    pid: /\d*/,
  }
  get '/p/(*all)', to: 'index#pages', as: :pages

  namespace :iot do
    post 'sharepay', to: 'sharepay#index'
    post 'sharepay/switch_login', to: 'sharepay#switch_login'
    post 'sharepay/switch_register', to: 'sharepay#switch_register'
    post 'sharepay/continue_as', to: 'sharepay#continue_as'
    post 'sharepay/login', to: 'sharepay#login'
    post 'sharepay/register', to: 'sharepay#register'
    post 'sharepay/verify', to: 'sharepay#verify'
    post 'sharepay/pay', to: 'sharepay#pay'


    post 'sharepay/request', to: 'sharepay#payment_request'
    post 'sharepay/signin', to: 'sharepay#signin'
    post 'sharepay/signup', to: 'sharepay#signup'
    post 'sharepay/do/payment', to: 'sharepay#do_request_page'
    get 'test', to: 'sharepay#test'
  end

  namespace :ajax, format: true, constraints: { format: :json } do
    get :startup, to: 'startup#index'

    scope module: :auth do
      # registration
      post 'phone_register', to: 'registration#phone'
      post 'email_register', to: 'registration#email'
      # verification
      post 'phone_verify', to: 'verification#phone'
      post 'email_verify', to: 'verification#email'
      # resend
      post 'phone_verify_resend', to: 'verification#phone_resend'
      post 'email_verify_resend', to: 'verification#email_resend'
      # sessions
      post 'facebook_login_callback', to: 'sessions#facebook'
      post 'phone_login', to: 'sessions#phone'
      post 'email_login', to: 'sessions#email'
      delete 'logout', to: 'sessions#destroy'
    end

    namespace :api do
      # CONTRACT
      # /client/contract/getMyContractUnreadCount
      # post 'contract/calendar', to: 'contract#calendar' #
      # post 'contract/cancel', to: 'contract#cancel'
      # post 'contract/end_contract', to: 'contract#end_contract'
      # post 'contract/find_can_report', to: 'contract#find_can_report' #
      # post 'contract/get_my_contract', to: 'contract#get_my_contract' #
      # post 'contract/get_our_contracts', to: 'contract#get_our_contracts' #
      # post 'contract/get_report', to: 'contract#get_report'
      # post 'contract/get', to: 'contract#get' #
      # post 'contract/image_upload', to: 'contract#image_upload'
      # post 'contract/item_create', to: 'contract#item_create'
      # post 'contract/item_update', to: 'contract#item_update'
      # post 'contract/logs', to: 'contract#logs'
      # post 'contract/read', to: 'contract#read'
      # post 'contract/receive_goods', to: 'contract#receive_goods'
      # post 'contract/reject', to: 'contract#reject'
      # post 'contract/report', to: 'contract#report'
      # post 'contract/return_goods', to: 'contract#return_goods'
      # post 'contract/score', to: 'contract#score'

      # post 'contract/service_end', to: 'contract#service_end'
      # post 'contract/service_update', to: 'contract#service_update'
      # post 'contract/ship_goods', to: 'contract#ship_goods'
      # post 'contract/sign', to: 'contract#sign'
      # post 'contract/space_create', to: 'contract#space_create'
      # post 'contract/space_end', to: 'contract#space_end'
      # post 'contract/space_update', to: 'contract#space_update'

      #ITEM
      # post 'item/item_add', to: 'item#item_add'
      # post 'item/item_update', to: 'item#item_update'
      # post 'item/space_add', to: 'item#space_add'
      # post 'item/space_update', to: 'item#space_update'
      # post 'item/get_item', to: 'item#get_item' #
      # post 'item/get_item_by_name', to: 'item#get_item_by_name' #
      # post 'item/remove_items', to: 'item#remove_items' #
      # post 'item/relative_item', to: 'item#relative_item' #
      # post 'item/report', to: 'item#report' #
      # post 'item/category_list', to: 'item#category_list' #
      # post 'item/message', to: 'item#message' #
      # post 'item/message_add', to: 'item#message_add' #

      #SYNC
      # post 'sync/notification', to: 'sync#notification' #
      # post 'sync/notification_unread', to: 'sync#notification_unread' #
      # post 'sync/notification_unread_count', to: 'sync#notification_unread_count' #
      # post 'sync/notification_read', to: 'sync#notification_read' #

      #USERPROFILE
      # post 'userprofile/search', to: 'userprofile#search' #
      # post 'userprofile/fb_user_update_name', to: 'userprofile#fb_user_update_name'
      # post 'userprofile/track_count', to: 'userprofile#track_count' #
      # post 'userprofile/get_track_user', to: 'userprofile#get_track_user' #
      # post 'userprofile/bank_info_auto_wire', to: 'userprofile#bank_info_auto_wire' #
      # post 'userprofile/bank_info_request_out', to: 'userprofile#bank_info_request_out' #

      #WISHLIST
      #post 'wishlist/save', to: 'wishlist#save' #
      #post 'wishlist/search', to: 'wishlist#search' #
      #post 'wishlist/remove', to: 'wishlist#remove' #
    end

    scope module: :api do
      # =========== CHAT ROOM 聊天室 =================
      post 'sync_chat_rooms', to: 'sync#chat_rooms'
      post 'chat/logs', to: 'sync#chat_logs'
      post 'chat/get_openfire_login_token', to: 'internal#get_openfire_login_token'
      #PROFILE
      post 'get_track_count', to: 'userprofile#track_count' #
      post 'get_comments_count', to: 'userprofile#comments_count' #
      post 'check_track', to: 'userprofile#is_tracked' #
      post 'add_track', to: 'userprofile#track' #
      post 'remove_track', to: 'userprofile#untrack' #
      post 'get_track', to: 'userprofile#get_track_user' #

      #PAYMENT
      post 'creditcard_payment', to: 'payment#pay_creditcard'
      post 'get_paymentinfo', to: 'payment#get_order'

      #SEARCH
      post 'multi', to: 'search#multi_search' #
      post 'search_user', to: 'userprofile#search' #
      post 'search_item', to: 'item#get_item_by_name' #
      post 'serach_wish', to: 'wishlist#search' #

      #NOTIFICATION
      post 'get_unread_notify', to: 'sync#notification_unread' #
      post 'count_unread_notify', to: 'sync#notification_unread_count' #
      post 'get_notify', to: 'sync#notification_read' #
      post 'get_notify_contract', to: 'contract#get_unread_contract' #

      #SUE
      post 'send_sue_request', to: 'contract#report'
      post 'get_sue_report', to: 'contract#get_report'

      #CONTRACT
      post 'get_my_unread_count', to: 'contract#get_my_unread_count'
      post 'check_item_ongoing', to: 'contract#check_item_ongoing'
      post 'reserve_space', to: 'contract#space_create'
      post 'reserve_space_update', to: 'contract#space_update'
      post 'reserve_goods', to: 'contract#item_create'
      post 'reserve_goods_update', to: 'contract#item_update'
      post 'reserve_used_goods', to: 'contract#used_item_create'
      post 'reserve_used_goods_update', to: 'contract#used_item_update'
      post 'reserve_service', to: 'contract#service_create'
      post 'reserve_service_update', to: 'contract#service_update'
      post 'get_my_order', to: 'contract#get_my_contract' #
      post 'reject_order', to: 'contract#reject' #
      post 'cancel_order', to: 'contract#cancel' #
      post 'accept_order', to: 'contract#sign' #
      post 'ship_item_goods', to: 'contract#ship_goods' #
      post 'return_item_goods', to: 'contract#return_goods' #
      post 'receive_confirm', to: 'contract#receive_goods' #
      post 'score_order', to: 'contract#score' #
      post 'end_service', to: 'contract#service_end' #
      post 'end_space', to: 'contract#space_end' #
      post 'get_ship_order', to: 'ship#order' #
      post 'create_ship_order', to: 'ship#create' #
      post 'get_ship_log', to: 'ship#log' #
      post 'upload_image_record', to: 'contract#image_upload' #

      #PAYMENT
      post 'get_balance_list', to: 'payment#search'

      #CALENDAR
      post 'get_calendar', to: 'contract#calendar' #

      #MESSAGEBOARD
      post 'get_message_board', to: 'item#message' #
      post 'add_message', to: 'item#message_add' #

      #OREDERDETAIL
      post 'get_order', to: 'contract#get' #
      post 'get_order_images', to: 'contract#images'
      post 'get_order_logs', to: 'contract#logs'
      post 'send_read', to: 'contract#read'

      #COMMENTS
      post 'get_owner_comments', to: 'userprofile#owner_comments' #
      post 'get_lessee_comments', to: 'userprofile#lessee_comments' #

      #MARKETING
      post 'get_coupon', to: 'marketing#coupon_list' #

      #FOLLOW
      post 'add_follow', to: 'userprofile#track' #
      post 'remove_follow', to: 'userprofile#untrack'
      post 'check_follow', to: 'userprofile#is_tracked' #

      #FAVORITE
      post 'add_fav', to: 'favorite#add' #
      post 'get_fav', to: 'favorite#my_favorite' #
      post 'remove_fav', to: 'favorite#remove' #

      # ITEM
      post 'get_user_items', to: 'item#get_item_by_user' #
      post 'delete_item', to: 'item#remove_items' #
      post 'item_detail', to: 'item#view_item' #
      post 'create_goods_item', to: 'item#item_add'
      post 'update_goods_item', to: 'item#item_update'
      post 'create_used_goods_item', to: 'item#used_item_add'
      post 'update_used_goods_item', to: 'item#used_item_update'
      post 'create_service_item', to: 'item#service_add'
      post 'update_service_item', to: 'item#service_update'
      post 'create_space_item', to: 'item#space_add'
      post 'update_space_item', to: 'item#space_update'
      post 'send_report', to: 'item#report' #
      # WISHLIST
      post 'wish/save', to: 'wishlist#save' #
      post 'get_wish_pond', to: 'wishlist#search' #
      post 'get_wish', to: 'wishlist#get' #
      post 'wish/remove', to: 'wishlist#remove' #

      # MARKETING
      get 'my_coupons', to: 'marketing#coupon_list'
      post 'store_result', to: 'ship#store_result'
      # ITEMS
      scope :item do
        post 'list', to: 'item#search_item_list'
      end

      # ======================================

app/models/api/iot/create_account_by_order.rb
class Api::Iot::CreateAccountByOrder < ApiIotBase

  PATH = '/register/regist/payment/order';

  def path
    PATH
  end

  def request_method
     :post
  end

end

app/models/api/iot/regist_order.rb
class Api::Iot::RegisOrder < ApiIotBase

  PATH = '/regist/order';

  def path
    PATH
  end

  def request_method
     :post
  end

end

app/models/concerns/iot/user.rb
module Iot
  module User
    extend ActiveSupport::Concern

    included do
      attr_accessor :user_login_as,
                    :email_exist, :phone_exist,
                    :user_profile,
                    :current_user,
                    :user_been_checked


      def check_user_login current_user
        raise 'Need check user exist first' unless self.user_been_checked
        return if current_user.nil?
        if phone_exist? && phone === current_user['phone']
          self.user_login_as = phone and return
        end
        if email_exist? && email === current_user['email']
          self.user_login_as = email and return
        end
      end

      def is_user_login?
        self.user_login_as.present?
      end

      def request_user_data current_user
        uid = current_user['uid']
        return 'Uid not exist' if uid.nil?
        user_general_info = ::Api::Userprofile::UserGeneralInfo.new uid: uid
        user_general_info.request
        self.user_profile = user_general_info.response_data['user_profile']
      end

      def request_check_user_being
        params = initial_params.slice :email, :phone
        check = ::Api::Register::AccountIsExist.new params
        check.request
        self.email_exist = check.response_data['email_exist']
        self.phone_exist = check.response_data['phone_exist']
        self.user_been_checked = true
      end

      def email_exist?
        email_exist || false
      end

      def phone_exist?
        phone_exist || false
      end

      def is_user_exist?
        phone_exist? || email_exist?
      end

      def user
        OpenStruct.new user_profile
      end

      def login_user password, browser_info
        params = {}
        params['password'] = password
        if user_login_as === phone
          params['phone'] = phone
          session = ::Auth::Session::LoginMobile.new(params, browser_info)
        elsif user_login_as === email
          params['email'] = email
          session = ::Auth::Session::LoginEmail.new(params, browser_info)
        else
          # do nothing
        end
        session.request
        self.current_user = session.warden_session
        session
      end
    end
  end
end

app/models/iot/api/base.rb
module Iot
  module Api
    class Base
      include HTTParty
      base_uri Settings.api_iot_base_uri
      HEADERS = { 'Content-Type' => 'application/json', 'Accept' => 'application/json' }
      headers HEADERS

      attr_accessor :error_message, :error_code,
                    :response_data, :response_result, :response_headers,
                    :iottoken, :request_params

      def initialize params = nil, token = nil
        self.request_params = params
        self.iottoken = token
      end

      def request_method
        :post
      end

      def request_api
        response = http_request

        case response.code
        when 200
          response
        when 404
          raise 'NOT FOUND'
        else
          raise "ZOMG ERROR #{response.inspect} #{path}"
        end
      end

      def request
        response = self.request_api
        if response.has_key? 'result'
          self.response_result = response['result']
          self.error_code = response['result']['code']
        end
        self.response_data = response['data'] if response.has_key?('data')
        self.response_headers = response.headers
        handle_response_error response
      end

      def handle_response_error response
        case response.code
        when 200
          true
        else
          false
        end
      end

      # def request_params
      #   @params
      # end
      #
      # def request_params=(values)
      #   @params = values
      # end

      def path
        raise 'Need defind in subclass.'
      end

      protected
      def request_body
        self.request_params.to_json
      end

      def request_headers
        HEADERS.merge IoT_Token: self.iottoken
      end

      def http_request
        case self.request_method.to_sym
        when :post
          self.class.post path, body: request_body, headers: request_headers
        when :get
          self.class.get path, headers: request_headers
        else
          raise 'Need request method'
        end
      end
    end
  end
end

app/models/iot/api/create_account_by_order.rb
class Iot::Api::CreateAccountByOrder < ApiIotBase

  PATH = '/register/regist/payment/order';

  def path
    PATH
  end

  def request_method
    :post
  end

end

app/models/iot/api/login.rb
module Iot
  module Api
    class Login < Base

      def path
        '/session/IoTAccount/login'
      end

      def request_method
         :post
      end
    end
  end
end

app/models/iot/api/order_bind_with_user.rb
module Iot
  module Api
    class OrderBindWithUser < Base

      def path
        '/payment/handler/order/bind_with_user'
      end

      def request_method
         :post
      end
    end
  end
end

app/models/iot/api/regist_order.rb
class Iot::Api::RegisOrder < ApiIotBase

  PATH = '/regist/order';

  def path
    PATH
  end

  def request_method
     :post
  end

end

app/models/iot/api/server_login.rb
module Iot
  module Api
    class ServerLogin < Base

      CERTIFICATION = 'mYteQnom66OAOYkwnxXcyMSual3bM0qLzWlDGsmr+DrJ6yEpMQBxjTrgoVh8O3lVNqoAb2DY+DpqYZteGLX+WzRUN1SBeF93iCWqNpd7ICg='
      SHAREEC_CLIENT_UID = 'SAI_CA_B0009E2O'

      def path
        '/session/server/login'
      end

      def request_method
         :post
      end

      def initialize params = nil, token = nil
        super
        self.request_params = {
          client_app_uid: SHAREEC_CLIENT_UID,
          certification: CERTIFICATION,
        }
      end
    end
  end
end

app/models/iot/esun_form.rb
module Iot
  class EsunForm
    include ActiveModel::Model

    attr_accessor :data, :mac, :ksn, :redirect
  end
end

app/models/iot/pay/base.rb
module Iot
  module Pay
    class Base
      include ActiveModel::Model
      include ActiveModel::Validations
      include ActionView::Helpers::NumberHelper

      attr_accessor :resource_app_uid,
                    :resource_app_order_no,
                    :app_user_pk,
                    :user_name,
                    :email, :phone,
                    :product_name, :product_desc, :price, :unit, :checksum, :arg,
                    :return_url,
                    :current_user,
                    :user_login_as


      validate :email_or_phone_present

      def initialize params, current_user = nil
        super params
        self.current_user = current_user
        @initial_params = params.to_h
      end

      def initial_params
        @initial_params
      end


      def formatted_price
        "NTD #{number_to_currency(price, precision: 0)}"
      end

      protected
      def email_or_phone_present
        if email.blank? && phone.blank?
          errors.add(:email_or_phone, 'At least email or phone.')
        end
      end
    end
  end
end

app/models/response_json/iot/login.rb
class ResponseJson::Iot::Login
  class << self
    def structure
      {
        uid: nil,
        #  -string
        name: nil,
        #  -string
        token: nil,
        #  -string
      }
    end
  end
end

app/views/iot/sharepay/_footer.html.haml
.iot.footer
  .container
    .logo-container
      .partner 合作夥伴
      .logo
    .navs-container
      .navs
        .nav= link_to '關於ShareApp', 'https://www.shareapp.com.tw/about'
        .nav= link_to '前往網站', 'https://web.shareapp.com.tw'

app/views/iot/sharepay/_login_form.html.haml
= form_for @login, url: iot_sharepay_do_login_path, method: :post, as: :login do |f|
  = f.text_field :email
  = f.text_field :phone
  = f.text_field :password
  = f.fields_for :payment, @login.payment do |nf|
    = render partial: 'payment', locals: { f: nf }
  = f.submit '登入', class: 'button'

app/views/iot/sharepay/_payment.html.erb
<%= f.hidden_field :resource_app_uid %>
<%= f.hidden_field :resource_app_order_no %>
<%= f.hidden_field :product_name %>
<%= f.hidden_field :product_desc %>
<%= f.hidden_field :price %>
<%= f.hidden_field :unit %>
<%= f.hidden_field :app_user_pk %>
<%= f.hidden_field :user_name %>
<%= f.hidden_field :email %>
<%= f.hidden_field :phone %>
<%= f.hidden_field :checksum %>
<%= f.hidden_field :arg %>
<%= f.hidden_field :return_url %>

app/views/iot/sharepay/_payment_detail.html.haml
%h1.title.text-center 線上繳款
.row-header
  .title.black-color
    付款資訊
    %span.helper.danger-color 請先確認以下資訊再進行付款
.row-body
  .payment-detail.bg.light-blue
    %table
      %tbody
        %tr
          %th 訂單編號：
          %td= @payment.resource_app_order_no
        %tr
          %th 商品名稱：
          %td= @payment.product_name
        %tr
          %th 商品介紹：
          %td= @payment.product_desc
        %tr
          %th 商店名稱：
          %td 收多易
        %tr
          %th 應付金額：
          %td= @payment.formatted_price

app/views/iot/sharepay/_verify_hidden.html.haml
= f.hidden_field :identify_by
= f.hidden_field :auth_email
= f.hidden_field :auth_phone
= f.hidden_field :password
= f.hidden_field :name

app/views/iot/sharepay/continue_as.html.haml
#continue_as.iot.container
  .row.profile
    .avatar
      - if @payment.user.picture.present?
        = image_tag @payment.user.picture
    .login-as.main-color.text-center
      = @payment.user.name
      %br
      = @payment.user_login_as
  .row.controls.text-center
    = form_for @payment, as: :payment, url: iot_sharepay_continue_as_path do |f|
      = render partial: 'payment', locals: { f: f }
      = f.submit "繼續使用此帳號付款?", class: 'button primary-button continue'
    = form_for @payment, as: :payment, url: iot_sharepay_switch_login_path do |f|
      = render partial: 'payment', locals: { f: f }
      = f.submit '使用別的帳號登入', class: 'button primary-button switch'
    = form_for @payment, as: :payment, url: iot_sharepay_switch_register_path do |f|
      = render partial: 'payment', locals: { f: f }
      = f.submit '建立新帳號', class: 'button primary-button switch'

app/views/iot/sharepay/index.html.haml
#request_page
  .board
    .title 線上繳款
    .blue-background
      .subtitle
        %span.subtitle-text 付款資訊
        %span.subtitle-hint 請先確認已下資訊是否正確再進行付款
      %table.table
        %tbody
          %tr
            %th{:width => "100"} 訂單編號：
            %td= @payment.resource_app_order_no
          %tr
            %th 商品名稱：
            %td= @payment.product_desc
          %tr
            %th 商品介紹：
            %td= @payment.product_desc
          %tr
            %th 付款商店：
            %td 收多易
          %tr
            %th 付款總金額：
            %td= @payment.formatted_price
    .subtitle
      %span.subtitle-text 聯絡資訊
      %span.subtitle-hint 為了避免日後交易問題，我們需要請您註冊帳號，留下聯絡方式
      .board-radio
        %input{:checked => "checked", :name => "login_type", :onchange => "onLoginChg(0)", :type => "radio", :value => "account"}/
        我已經有帳號了
        %br/
        %input{:name => "login_type", :onchange => "onLoginChg(1)", :type => "radio", :value => "create"}/
        建立帳號
        %br/
      #login-board.board-visible
        - if @login.login_error.present?
          .errors= '帳號或密碼錯誤'
        = form_for @login, as: :request, url: iot_sharepay_signin_path, method: 'post' do |f|
          %div
            .form-text 帳號：
            = f.text_field :account, class: 'board-input'
          %div
            .form-text 密碼：
            = f.text_field :password, class: 'board-input'
          = f.submit '登入', class: 'button form-button'
          = render partial: 'payment', locals: { f: f }
      #create-board.board-hidden
        = form_for @registration, as: :request, url: iot_sharepay_signup_path, method: 'post' do |f|
          %div
            .form-text 帳號名稱：
            = f.text_field :account, class: 'board-input'
          %div
            .form-text 設定密碼：
            = f.text_field :password, class: 'board-input'
          %div
            .form-text 再輸一次密碼：
            = f.text_field :password_confirmation, class: 'board-input'
          .form-top-space
            .form-text 付款人名稱：
            = f.text_field :user_name, class: 'board-input'
          %div
            .form-text 聯絡電話：
            = f.text_field :phone, class: 'board-input'
          %div
            .form-text 聯絡信箱：
            = f.text_field :email, class: 'board-input'
          = f.submit '建立帳號', class: 'button form-button'
          = render partial: 'payment', locals: { f: f }
:javascript
  function onLoginChg(selected) {
    var loginBoard = document.getElementById("login-board").classList;
    var createBoard = document.getElementById("create-board").classList;
    if (selected) {
      loginBoard.remove("board-visible");
      loginBoard.add("board-hidden");
      createBoard.remove("board-hidden");
      createBoard.add("board-visible");
    } else {
      loginBoard.remove("board-hidden");
      loginBoard.add("board-visible");
      createBoard.remove("board-visible");
      createBoard.add("board-hidden");
    }
  }

app/views/iot/sharepay/login.html.haml
.iot.container.pay
  %h1.title.text-center 線上繳款
  .row-header
    .title.black-color
      付款資訊
      %span.helper.danger-color 請先確認以下資訊再進行付款
  .row-body
    .payment-detail.bg.light-blue
      %table
        %tbody
          %tr
            %th 訂單編號：
            %td= @payment.resource_app_order_no
          %tr
            %th 商品名稱：
            %td= @payment.product_name
          %tr
            %th 商品介紹：
            %td= @payment.product_desc
          %tr
            %th 商店名稱：
            %td 收多易
          %tr
            %th 應付金額：
            %td= @payment.formatted_price
  .row-header
    .title.black-color
      聯絡資訊
      %span.helper.danger-color 為了避免日後交易問題，我們需要請您註冊帳號，留下聯絡方式
  .row-body
    - if @login.errors.messages.length > 0
      .error-messages
        - @login.errors.messages.each do |key, message|
          .error-message= message.first
    = form_for @login, url: iot_sharepay_login_path, method: :post, as: :payment, html: { id: :login_form } do |f|
      .input-group
        = f.label :auth_email, class: 'label' do
          Email 登入
          .radio-container= f.radio_button :identify_by, :email
        = f.text_field :auth_email, class: 'input', disabled: !@login.identify_by_email?
      .input-group
        = f.label :auth_phone, class: 'label' do
          手機登入
          .radio-container= f.radio_button :identify_by, :phone
        = f.text_field :auth_phone, class: 'input', disabled: !@login.identify_by_phone?
      .input-group
        = f.label :password, '密碼', class: 'label'
        = f.password_field :password, class: 'input'
      = render partial: 'payment', locals: { f: f }
      .input-group
        %label.label
        = f.submit '登入', class: 'button primary-button'

:css
  .input-group {

  }

:javascript
  var $loginByEmail = document.getElementById('payment_identify_by_email');
  var $loginByPhone = document.getElementById('payment_identify_by_phone');
  var $emailInput = document.getElementById('payment_auth_email');
  var $phoneInput = document.getElementById('payment_auth_phone');
  $loginByEmail.addEventListener('change', function(e) {
    $phoneInput.setAttribute('disabled', 'disabled');
    $emailInput.removeAttribute('disabled');
  });
  $loginByPhone.addEventListener('change', function(e) {
    $emailInput.setAttribute('disabled', 'disabled');
    $phoneInput.removeAttribute('disabled');
  });

app/views/iot/sharepay/register.html.haml
.iot.container.pay
  = render 'payment_detail'
  .row-header
    .title.black-color
      聯絡資訊
      %span.helper.danger-color 為了避免日後交易問題，我們需要請您註冊帳號，留下聯絡方式
  .row-body
    - if @registration.errors.messages.length > 0
      .error-messages
        - @registration.errors.messages.each do |key, message|
          .error-message= message.first
    = form_for @registration, url: iot_sharepay_register_path, method: :post, as: :payment, html: { id: :register_form } do |f|
      .input-group
        = f.label :auth_email, class: 'label' do
          Email 註冊
          .radio-container= f.radio_button :identify_by, :email
        = f.text_field :auth_email, class: 'input', disabled: !@registration.identify_by_email?
      .input-group
        = f.label :auth_phone, class: 'label' do
          手機註冊
          .radio-container= f.radio_button :identify_by, :phone
        = f.text_field :auth_phone, class: 'input', disabled: !@registration.identify_by_phone?
      .input-group
        = f.label :password, '密碼', class: 'label'
        = f.password_field :password, class: 'input'
      .input-group
        = f.label :password_confirmation, '確認密碼', class: 'label'
        = f.password_field :password_confirmation, class: 'input'
      .input-group
        = f.label :name, '姓名', class: 'label'
        = f.text_field :name, class: 'input'
      = render partial: 'payment', locals: { f: f }
      .input-group
        %label.label
        = f.submit '註冊', class: 'button primary-button'

:javascript
  var $identifyByEmail = document.getElementById('payment_identify_by_email');
  var $identifyByPhone = document.getElementById('payment_identify_by_phone');
  var $emailInput = document.getElementById('payment_auth_email');
  var $phoneInput = document.getElementById('payment_auth_phone');
  var switchOnEmail = function() {
    $phoneInput.setAttribute('disabled', 'disabled');
    $emailInput.removeAttribute('disabled');
  };
  var switchOnPhone = function() {
    $emailInput.setAttribute('disabled', 'disabled');
    $phoneInput.removeAttribute('disabled');
  }
  $identifyByEmail.addEventListener('change', function(e) {
    switchOnEmail();
  });
  if ($identifyByEmail.checked) {
    switchOnEmail();
  }

  $identifyByPhone.addEventListener('change', function(e) {
    switchOnPhone();
  });
  if ($identifyByPhone.checked) {
    switchOnPhone();
  }

app/views/iot/sharepay/verification.html.haml
%h1 VERIFYCATION
= form_for @verification,  url: iot_sharepay_verify_path,
                    method: :post, as: :payment,
                    html: { id: :verifycation_form } do |f|
  .input-group
    = f.text_field :verify_code
  = render partial: 'payment', locals: { f: f }
  = f.submit '驗證', class: 'button'